<a href="https://colab.research.google.com/github/iamchenchu/Deep-Learnig-with-TensorFlow/blob/main/00_tensorFlow_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
# In this notebook we're going to learn some of the basic fundamental concepts of tensors using the TensorFlow

**Specifically:**

1. Introduction to tensors
2. Getting the informations from the tensors
3. Manipulating tensors
4. Tensors & Numpy
5. Using @tf.function (A way to speed up your regular Python functions)
6. Using the GPUs with TensorFlow(or TPUs)
7. Exercises to try for yourself

In [35]:
## introduction to tensors

In [36]:
#import TensorFlow

import tensorflow as tf
print(tf.__version__)

2.14.0


In [37]:
#creating tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [38]:
#check the number of dimensions of the tensor
scalar.ndim

0

In [39]:
#create a vecor
vector = tf.constant([10,10])
vector


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [40]:
#check the number of dimension
vector.ndim

1

In [41]:
#create a matrix which has more than 1 dimension

matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [42]:
#check the number of dimensions for the matrix

matrix.ndim

2

In [43]:
#create another matrix

another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]], dtype=tf.float16) # specify the data type
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [44]:
#number of dimensions

another_matrix.ndim

2

In [45]:
# let's create a tensor
tensor = tf.constant([[[1,2,3],
                      [4,5,6]],

                      [[7,8,9],
                     [10,11,12]],

                     [[13,14,15],
                      [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [46]:
tensor.ndim

3

**What we have learned so far**

1. Scalar : a single number
2. Vector : a number with direction (Ex : wind speed with the direction)
3. Matrix : a 2-Dimensional  array of numbers
4. Tensor : an n-dimensional array  of numbers (Where n can be any number, a 0-Dimensinal tensor is a scalar, a 1- dimension tensor is called a vector)



**Creating the tensors with tf.Variable**




In [47]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [48]:
# creating the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [50]:
#Let's try change one of the elements in the changeable tensor

changeable_tensor[0]= 7
changeable_tensor               # TypeError: 'ResourceVariable' object does not support item assignmentVariable

TypeError: ignored

In [ ]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor                 # it works well and give the output as <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>


**Variable vs Constant**

The tensors which we create using the tf.Variables can be modified using the assign() function as per our requirement

The tensors which we create using the tf.constant can not be modified. We use this way when a tensor should be unchangeable

Note: Rarely in practice will you need to decide whether to use tf.constant or tf. variable to create tensors, as TensorFlow does this for
you. However, if in doubt, use tf.Variable and change it later if needed.

In [51]:
# creating the random tensors
# Random tensors are tensors of some abirary size which contain random numbers
# create 2 random (but the same) tensors
# a function that represents the distribution of many random variables as a symmetrical bell-shaped graph.

random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

random_1 , random_2, random_1 == random_2

#Are they equal ? : Yes they are equal

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [52]:
## shuffle the order of elements in the tensor
#Sffule a tensor(valueable for when you want to shuffle the data so that inherent doesn't effect the learning)

not_shuffled = tf.constant([[10,7],
                           [3,4],
                           [2,5]])
not_shuffled.ndim # out put is 2


2

In [53]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [54]:
# how can we shuffle a tensor  : -> tf.random.shuffle()

tf.random.shuffle(not_shuffled) # order of the output would be changed


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [55]:
tf.random.shuffle(not_shuffled) # order of the output would be changed, everytime we run it it would kee changing


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [56]:
# after setting the seed, we will have the same everytime
# if we want our shuffled tensors to be in the same order, we've got to use the global level random seed as well as the operation level random seed


tf.random.set_seed(42) # Global level random seed
tf.random.shuffle(not_shuffled, seed = 42) # Operational level random seed


 # if we use only operational level random seed, our shuffled tensor keep changing when ever we run the code


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [57]:
## other ways to make tensors

tf.ones([10,7]) # creates a tensor of all ones with size of 10 rows and 7 columns


<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [60]:
tf.zeros([10,10]) # creates a tensor of all zeros with size of 10 rows and 10 columns

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [59]:
tf.zeros(shape=(3,4)) # creates a tensor of all zeros of float and the 3*4 size

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

***You can also turn Numpy arrays into tensors***

The main diffrence betweem Numpy arrays and TensorFlow tensors is that the tensors can be run on GPU computing

In [61]:
 # You can also turn Numpy arrays into tensors

import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32) # create a Numpy array between 1 and 25
numpy_A

# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [62]:
A = tf.constant(numpy_A) # converting the numpy array to a tensor
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [63]:
A = tf.constant(numpy_A, shape=(2,3,4)) # creates a 3 dimentional tensor, 2*3*4 = 24 which exactly matches with the number elements otherwise it will be an error
B = tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

***Getting information from our tensors***

When dealing with the tensors you should be familiar with the below terms

* Shape  : The length (number of elements) of each of the dimension of a tensor  **tensor.shape**
* Rank   : The number of tensor dimensions. A scalar has rank 0, vector has rank 1, a matrix has rank 2, a tensor has rank n **tensor.ndim**
* Axis or dimension : A perticular dimension of a tensor **tensor[0],tensor[:, 1]**
* Size :  The total number of items in the tensor.    **tf.size(tensor)**



In [64]:
# create a rank 4 tensor (4 dimentions)

rank_4_tensor = tf.zeros(shape=(2,3,4,5)) # 2 is number axises, 3 is number of matrix in each axis, 4 is number of rows, 5 number of colums
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [65]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [66]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [67]:
# Get various attributes of our tensor
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions: ",rank_4_tensor.ndim)
print("Shape of the tensor :",rank_4_tensor.shape)
print("Elements along 0 axis", rank_4_tensor.shape[0])
print("Elemets along the last axis :", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor :",tf.size(rank_4_tensor))
print("Total number of elements in our tensor :",tf.size(rank_4_tensor).numpy()) # converting to numpy number for better understanding

Datatype of every element:  <dtype: 'float32'>
Number of dimensions:  4
Shape of the tensor : (2, 3, 4, 5)
Elements along 0 axis 2
Elemets along the last axis : 5
Total number of elements in our tensor : tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor : 120


***Indexing the tensors***


Tensors can be indexed just like lists in the python


In [68]:
# Get the first  2 elements in the each dimension
some_list = [1,2,3,4]
some_list[:2]


[1, 2]

In [69]:
rank_4_tensor[:2,:2,:2,:2] # Get the first  2 elements in the each dimension

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [70]:
# Get the first element from each dimension from each index except the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [71]:
# Get the first element from each dimension from each index except the second last one
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [72]:
# Get the first element from each dimension from each index except the third last one
rank_4_tensor[:1, :, :1, :1]

<tf.Tensor: shape=(1, 3, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]],

        [[0.]]]], dtype=float32)>