<a href="https://colab.research.google.com/github/iamchenchu/Deep-Learnig-with-TensorFlow/blob/main/00_tensorFlow_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# In this notebook we're going to learn some of the basic fundamental concepts of tensors using the TensorFlow

**Specifically:**

1. Introduction to tensors
2. Getting the informations from the tensors
3. Manipulating tensors
4. Tensors & Numpy
5. Using @tf.function (A way to speed up your regular Python functions)
6. Using the GPUs with TensorFlow(or TPUs)
7. Exercises to try for yourself

In [2]:
## introduction to tensors

In [3]:
#import TensorFlow

import tensorflow as tf
print(tf.__version__)

2.14.0


In [4]:
#creating tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
#check the number of dimensions of the tensor
scalar.ndim

0

In [6]:
#create a vecor
vector = tf.constant([10,10])
vector


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
#check the number of dimension
vector.ndim

1

In [8]:
#create a matrix which has more than 1 dimension

matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
#check the number of dimensions for the matrix

matrix.ndim

2

In [10]:
#create another matrix

another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]], dtype=tf.float16) # specify the data type
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [11]:
#number of dimensions

another_matrix.ndim

2

In [12]:
# let's create a tensor
tensor = tf.constant([[[1,2,3],
                      [4,5,6]],

                      [[7,8,9],
                     [10,11,12]],

                     [[13,14,15],
                      [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [13]:
tensor.ndim

3

**What we have learned so far**

1. Scalar : a single number
2. Vector : a number with direction (Ex : wind speed with the direction)
3. Matrix : a 2-Dimensional  array of numbers
4. Tensor : an n-dimensional array  of numbers (Where n can be any number, a 0-Dimensinal tensor is a scalar, a 1- dimension tensor is called a vector)



**Creating the tensors with tf.Variable**




In [14]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [15]:
# creating the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [16]:
#Let's try change one of the elements in the changeable tensor

#changeable_tensor[0]= 7
#changeable_tensor               # TypeError: 'ResourceVariable' object does not support item assignmentVariable

In [17]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor                 # it works well and give the output as <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

**Variable vs Constant**

The tensors which we create using the tf.Variables can be modified using the assign() function as per our requirement

The tensors which we create using the tf.constant can not be modified. We use this way when a tensor should be unchangeable

Note: Rarely in practice will you need to decide whether to use tf.constant or tf. variable to create tensors, as TensorFlow does this for
you. However, if in doubt, use tf.Variable and change it later if needed.

In [18]:
# creating the random tensors
# Random tensors are tensors of some abirary size which contain random numbers
# create 2 random (but the same) tensors
# a function that represents the distribution of many random variables as a symmetrical bell-shaped graph.

random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

random_1 , random_2, random_1 == random_2

#Are they equal ? : Yes they are equal

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [19]:
## shuffle the order of elements in the tensor
#Sffule a tensor(valueable for when you want to shuffle the data so that inherent doesn't effect the learning)

not_shuffled = tf.constant([[10,7],
                           [3,4],
                           [2,5]])
not_shuffled.ndim # out put is 2


2

In [20]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [21]:
# how can we shuffle a tensor  : -> tf.random.shuffle()

tf.random.shuffle(not_shuffled) # order of the output would be changed


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [22]:
tf.random.shuffle(not_shuffled) # order of the output would be changed, everytime we run it it would kee changing


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [23]:
# after setting the seed, we will have the same everytime
# if we want our shuffled tensors to be in the same order, we've got to use the global level random seed as well as the operation level random seed


tf.random.set_seed(42) # Global level random seed
tf.random.shuffle(not_shuffled, seed = 42) # Operational level random seed


 # if we use only operational level random seed, our shuffled tensor keep changing when ever we run the code


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [24]:
## other ways to make tensors

tf.ones([10,7]) # creates a tensor of all ones with size of 10 rows and 7 columns


<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [25]:
tf.zeros([10,10]) # creates a tensor of all zeros with size of 10 rows and 10 columns

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [26]:
tf.zeros(shape=(3,4)) # creates a tensor of all zeros of float and the 3*4 size

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

***You can also turn Numpy arrays into tensors***

The main diffrence betweem Numpy arrays and TensorFlow tensors is that the tensors can be run on GPU computing

In [27]:
 # You can also turn Numpy arrays into tensors

import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32) # create a Numpy array between 1 and 25
numpy_A

# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [28]:
A = tf.constant(numpy_A) # converting the numpy array to a tensor
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [29]:
A = tf.constant(numpy_A, shape=(2,3,4)) # creates a 3 dimentional tensor, 2*3*4 = 24 which exactly matches with the number elements otherwise it will be an error
B = tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

***Getting information from our tensors***

When dealing with the tensors you should be familiar with the below terms

* Shape  : The length (number of elements) of each of the dimension of a tensor  **tensor.shape**
* Rank   : The number of tensor dimensions. A scalar has rank 0, vector has rank 1, a matrix has rank 2, a tensor has rank n **tensor.ndim**
* Axis or dimension : A perticular dimension of a tensor **tensor[0],tensor[:, 1]**
* Size :  The total number of items in the tensor.    **tf.size(tensor)**



In [30]:
# create a rank 4 tensor (4 dimentions)

rank_4_tensor = tf.zeros(shape=(2,3,4,5)) # 2 is number axises, 3 is number of matrix in each axis, 4 is number of rows, 5 number of colums
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [31]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [32]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [33]:
# Get various attributes of our tensor
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions: ",rank_4_tensor.ndim)
print("Shape of the tensor :",rank_4_tensor.shape)
print("Elements along 0 axis", rank_4_tensor.shape[0])
print("Elemets along the last axis :", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor :",tf.size(rank_4_tensor))
print("Total number of elements in our tensor :",tf.size(rank_4_tensor).numpy()) # converting to numpy number for better understanding

Datatype of every element:  <dtype: 'float32'>
Number of dimensions:  4
Shape of the tensor : (2, 3, 4, 5)
Elements along 0 axis 2
Elemets along the last axis : 5
Total number of elements in our tensor : tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor : 120


***Indexing the tensors***


Tensors can be indexed just like lists in the python


In [34]:
# Get the first  2 elements in the each dimension
some_list = [1,2,3,4]
some_list[:2]


[1, 2]

In [35]:
rank_4_tensor[:2,:2,:2,:2] # Get the first  2 elements in the each dimension

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [36]:
# Get the first element from each dimension from each index except the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [37]:
# Get the first element from each dimension from each index except the second last one
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [38]:
# Get the first element from each dimension from each index except the third last one
rank_4_tensor[:1, :, :1, :1]

<tf.Tensor: shape=(1, 3, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]],

        [[0.]]]], dtype=float32)>

In [39]:
# create a rank 2 tensor which has 2 dimensions

rank_2_tensor = tf.constant([[10,7],
                             [3,4]])
rank_2_tensor.shape # prints the shape as TensorShape([2, 2])


TensorShape([2, 2])

In [40]:
rank_2_tensor.ndim # prints 2

2

In [41]:
some_list, some_list[-1]

([1, 2, 3, 4], 4)

In [42]:
#Get the last item of each of our row rank 2 tensor

rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [43]:
# Add in extra dimention to our rank 2 tensor

rank_3_tensor =rank_2_tensor[...,tf.newaxis] # ... means at the end , tf.newaxis adds the new axis to the current shape
# now new axis will be added as shape=(2, 2, 1) which means 2 axis , 2 matrix in each with 1 shape
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [44]:
 # Alternative to tf.newaxis

tf.expand_dims(rank_2_tensor, axis=-1) # -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [45]:
# expand the 0- axis
tf.expand_dims(rank_2_tensor, axis=0) # expand the 0- axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

**##Manipulating the tensors (Tensor Operations)**

Basic Operations :
"+","-","*","/"

In [46]:
tensor=tf.constant([[10,7],
                    [3,4]])
tensor + 10                             # adds 10 number to each element in this case

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [47]:
# Original tensor is unchanged we are trying to get the new tensor

tensor                 # u will get outpus as the origin tensor without 10 added to each element

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [48]:
# multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [49]:
# Substraction

tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [50]:
# We can use the tensorflow built in functions tooo

tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [51]:
tf.add(tensor,10)  # addition with inbuilt

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

**Matrix Multiplication**

In Machine Learning, matrix multiplication is very common computation.


-> For multiplying a matrix with another matrix could be done using the dot product

There are two rules for out tensors (Matrices) need to fulfill if we'are going to matrix multiply them:

1. The inner dimensions must match
2. The resulting matrix has the shape of the outer dimensions


In [52]:
#matrix multiplication in the tensorflow

print(tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [53]:
tf.matmul(tensor, tensor) # multiplying the tensor with a tensor is the dot multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [54]:
tensor * tensor  # this is just multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [55]:
# matrix multiplication  with python operator "@"

tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [56]:
tensor.shape

TensorShape([2, 2])

In [57]:
# Create a tensor (3 , 2) tensor

X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])

# Create a tensor (3 , 2) tensor
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])

In [58]:
X , Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [59]:
# Try to matrix multiply

# tf.matmul(X,Y)  # returns a error

#Lets change the shape of Y
tf.reshape(Y, shape=(2,3))



<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [60]:
# Now let's try to matrix multiply X by reshaped Y

X @ tf.reshape(Y , shape=(2,3))             # now it works and forms (3,3) matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [61]:
tf.matmul(X, tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [62]:
# now let's try to reshape the X and then try to do multiplication

tf.reshape(X, shape=(2,3)).shape, Y.shape # output is (TensorShape([2, 3]), TensorShape([3, 2]))

# int the above case as per the multiplication rules inner values of shape are matching so now will make 2 by 2 out values size matrix

(TensorShape([2, 3]), TensorShape([3, 2]))

In [63]:
tf.matmul(tf.reshape(X, shape=(2,3)),Y) # working as expected and creating the 2 by 2 matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [64]:
# Can do the same with the transpose

X, tf.transpose(X), tf.reshape(X, shape=(2,3))  # X is in 3 by 2 form, in transpose it makes rows as column an column as rows

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [65]:
# Try Matrix multiplication with transpose rather than reshape

tf.matmul(tf.transpose(X),Y)        # it works well as it will matches with the rules required

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**The Dot Product**

Matrix multiplication is also referred t as the dot product
You can perform Matrix multiplication using :

1. tf.matmul()
2. tf.tensordot()

In [66]:
#Perform the dot product on X and Y (Requires X or Y to be transposed)

tf.tensordot(tf.transpose(X), Y, axes =1) # 3 arguements X, Y are matrices for multiplication and 3rd argument is axes

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [67]:
#Perform matrix multiplication between X and Y (Transposed)

tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [68]:
# Perform matrix multiplication between X and Y (Reshaped)

tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [69]:
# Check the values of Y, reshape Y and transposed Y

print("Normal Y :")
print(Y,"\n")   # "\n" is a new line

print("Y reshaped to (2,3): ")
print(tf.reshape(Y, (2,3)),"\n")

print("Y transposed : ")
print(tf.transpose(Y))


Normal Y :
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3): 
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed : 
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [70]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
#Generally when performing the multiplication on tensors and one of the axeses does not line up, then u will transposed the one of
#the tensor rather than reshaping that to satify the matrix multiplation rules


**Change the data type of the tensor**



In [71]:
#Create a new tensor with default datatype (float32)

B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [72]:
C =tf.constant([7,10])
C.dtype

tf.int32

In [73]:
tf.__version__

'2.14.0'

In [76]:
# Change from float32 to float16 (Called reduce precision)

D = tf.cast(B, dtype =tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [79]:
#Change from int32 to float32

E = tf.cast(C, tf.float32)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>,
 tf.float32)

In [82]:
E_float16 = tf.cast(E, tf.float16)     # Change the float32 to float16
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

**Aggregating the tensors**

Aggretating tensors = condensing them from multiple values down to smaller amount of values

In [88]:
 # Get the absolute values

D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [89]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's Go through the following forms of aggregation :

*Get the Minimum

*Get the Maximum

*Get the mean of a tensor

*Get the sum of a tensor

In [90]:
#crate a random tensor with values of 0 and 100 of size 50

E = tf.constant(np.random.randint(0,100,50))
E


<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([27, 17,  8, 57, 24, 74, 13,  8, 22,  1, 15, 58, 66, 12, 63, 77, 39,
       44, 49, 81, 68, 56, 68, 55,  1, 58,  1, 20, 37, 30, 36, 31, 28, 39,
       31, 24, 14, 40, 46,  8, 91, 77, 13,  3, 83, 61, 84, 79, 48, 33])>

In [91]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [92]:
# finding the minimum

tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [93]:
# Find the maximum

tf.reduce_max(E)


<tf.Tensor: shape=(), dtype=int64, numpy=91>

In [94]:
# find the mean

tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=40>

In [95]:
# find the sum

tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2018>

Varience and standard deviation of a tensor in TensorFlow

In [107]:
# Let's find the Varience of the tensor

# tf.reduce_varience(E) # won't work
#TO find the varience of our tensor, we need access to tensorflow_probability

import tensorflow_probability as tfp

tfp.stats.variance(E)


<tf.Tensor: shape=(), dtype=int64, numpy=665>

In [108]:
# Find the Standard deviation

# the Input should be real or complex numbers we will cast our tensor to float here to qualify the rule

tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=25.794388>

**Find the positinal maximum and minimum**



In [111]:
# create a new tensor for finding the positional max and min
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [112]:
#Find the positional max
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [113]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [114]:
# Find the max value of F

tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [117]:
#Check the equality

F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [118]:
#Find the positional min

tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [119]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [123]:
#find the min value

F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [121]:
F[tf.argmin(F)] == tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

**Squeezing a tensor (Removing all single dimensions)**



In [124]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [126]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [128]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
        0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
        0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
        0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
        0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
        0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
        0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
        0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
        0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
        0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
       dtype=float32)>,
 TensorShape([50]))

**One- hot encoding**

In [130]:
# Create a list of indices

some_list = [0,1,2,3] # could be red, green, blue, purple

#One hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>